//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertPerson", ReplyAction="http://tempuri.org/IService/InsertPersonResponse")]
        int InsertPerson(DataTransferObjectLibrary.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertPerson", ReplyAction="http://tempuri.org/IService/InsertPersonResponse")]
        System.Threading.Tasks.Task<int> InsertPersonAsync(DataTransferObjectLibrary.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdatePerson", ReplyAction="http://tempuri.org/IService/UpdatePersonResponse")]
        int UpdatePerson(DataTransferObjectLibrary.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdatePerson", ReplyAction="http://tempuri.org/IService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<int> UpdatePersonAsync(DataTransferObjectLibrary.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePerson", ReplyAction="http://tempuri.org/IService/DeletePersonResponse")]
        int DeletePerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePerson", ReplyAction="http://tempuri.org/IService/DeletePersonResponse")]
        System.Threading.Tasks.Task<int> DeletePersonAsync(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonById", ReplyAction="http://tempuri.org/IService/GetPersonByIdResponse")]
        DataTransferObjectLibrary.Person GetPersonById(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonById", ReplyAction="http://tempuri.org/IService/GetPersonByIdResponse")]
        System.Threading.Tasks.Task<DataTransferObjectLibrary.Person> GetPersonByIdAsync(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllPerson", ReplyAction="http://tempuri.org/IService/GetAllPersonResponse")]
        DataTransferObjectLibrary.ListOfPerson GetAllPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllPerson", ReplyAction="http://tempuri.org/IService/GetAllPersonResponse")]
        System.Threading.Tasks.Task<DataTransferObjectLibrary.ListOfPerson> GetAllPersonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference.IService>, Client.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertPerson(DataTransferObjectLibrary.Person person) {
            return base.Channel.InsertPerson(person);
        }
        
        public System.Threading.Tasks.Task<int> InsertPersonAsync(DataTransferObjectLibrary.Person person) {
            return base.Channel.InsertPersonAsync(person);
        }
        
        public int UpdatePerson(DataTransferObjectLibrary.Person person) {
            return base.Channel.UpdatePerson(person);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePersonAsync(DataTransferObjectLibrary.Person person) {
            return base.Channel.UpdatePersonAsync(person);
        }
        
        public int DeletePerson(int personId) {
            return base.Channel.DeletePerson(personId);
        }
        
        public System.Threading.Tasks.Task<int> DeletePersonAsync(int personId) {
            return base.Channel.DeletePersonAsync(personId);
        }
        
        public DataTransferObjectLibrary.Person GetPersonById(int personId) {
            return base.Channel.GetPersonById(personId);
        }
        
        public System.Threading.Tasks.Task<DataTransferObjectLibrary.Person> GetPersonByIdAsync(int personId) {
            return base.Channel.GetPersonByIdAsync(personId);
        }
        
        public DataTransferObjectLibrary.ListOfPerson GetAllPerson() {
            return base.Channel.GetAllPerson();
        }
        
        public System.Threading.Tasks.Task<DataTransferObjectLibrary.ListOfPerson> GetAllPersonAsync() {
            return base.Channel.GetAllPersonAsync();
        }
    }
}
