//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: data-contract serialization ([DataContract]/[DataMember]) enabled
    
// Generated from: Person.proto
// Note: requires additional types generated from: descriptor.proto
namespace DataTransferObjectLibrary
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  [global::System.Runtime.Serialization.DataContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    public Person() {}
    

    private int _Id = (int)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Id", Order = 1, IsRequired = false)]
    
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _FirstName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"FirstName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"FirstName", Order = 2, IsRequired = true)]
    
    public string FirstName
    {
      get { return _FirstName; }
      set { _FirstName = value; }
    }
    private string _LastName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LastName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"LastName", Order = 3, IsRequired = true)]
    
    public string LastName
    {
      get { return _LastName; }
      set { _LastName = value; }
    }
    private readonly global::System.Collections.Generic.List<DataTransferObjectLibrary.PhoneNumber> _Phones = new global::System.Collections.Generic.List<DataTransferObjectLibrary.PhoneNumber>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Phones", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Phones", Order = 4, IsRequired = false)]
    
    public global::System.Collections.Generic.List<DataTransferObjectLibrary.PhoneNumber> Phones
    {
      get { return _Phones; }
    }
  

    private string _Email = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Runtime.Serialization.DataMember(Name=@"Email", Order = 5, IsRequired = false)]
    
    public string Email
    {
      get { return _Email; }
      set { _Email = value; }
    }

    private DataTransferObjectLibrary.DateTime _BirthDate = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"BirthDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    [global::System.Runtime.Serialization.DataMember(Name=@"BirthDate", Order = 6, IsRequired = false)]
    
    public DataTransferObjectLibrary.DateTime BirthDate
    {
      get { return _BirthDate; }
      set { _BirthDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhoneNumber")]
  [global::System.Runtime.Serialization.DataContract(Name=@"PhoneNumber")]
  public partial class PhoneNumber : global::ProtoBuf.IExtensible
  {
    public PhoneNumber() {}
    
    private string _Number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Number", Order = 1, IsRequired = true)]
    
    public string Number
    {
      get { return _Number; }
      set { _Number = value; }
    }
    private DataTransferObjectLibrary.PhoneNumber.PhoneType _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Type", Order = 2, IsRequired = true)]
    
    public DataTransferObjectLibrary.PhoneNumber.PhoneType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PhoneType")]
    [global::System.Runtime.Serialization.DataContract(Name=@"PhoneType")]
    public enum PhoneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROFESIONNAL", Value=1)]
      [global::System.Runtime.Serialization.EnumMember(Value=@"PROFESIONNAL")]
      PROFESIONNAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HOME", Value=2)]
      [global::System.Runtime.Serialization.EnumMember(Value=@"HOME")]
      HOME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=3)]
      [global::System.Runtime.Serialization.EnumMember(Value=@"MOBILE")]
      MOBILE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DateTime")]
  [global::System.Runtime.Serialization.DataContract(Name=@"DateTime")]
  public partial class DateTime : global::ProtoBuf.IExtensible
  {
    public DateTime() {}
    
    private int _Year;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Year", Order = 1, IsRequired = true)]
    
    public int Year
    {
      get { return _Year; }
      set { _Year = value; }
    }
    private int _Month;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Month", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Month", Order = 2, IsRequired = true)]
    
    public int Month
    {
      get { return _Month; }
      set { _Month = value; }
    }
    private int _Day;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Day", Order = 3, IsRequired = true)]
    
    public int Day
    {
      get { return _Day; }
      set { _Day = value; }
    }

    private int _Hour = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Hour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"Hour", Order = 4, IsRequired = false)]
    
    public int Hour
    {
      get { return _Hour; }
      set { _Hour = value; }
    }

    private int _Minute = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Minute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"Minute", Order = 5, IsRequired = false)]
    
    public int Minute
    {
      get { return _Minute; }
      set { _Minute = value; }
    }

    private int _Second = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"Second", Order = 6, IsRequired = false)]
    
    public int Second
    {
      get { return _Second; }
      set { _Second = value; }
    }

    private int _Millisecond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Millisecond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"Millisecond", Order = 7, IsRequired = false)]
    
    public int Millisecond
    {
      get { return _Millisecond; }
      set { _Millisecond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListOfPerson")]
  [global::System.Runtime.Serialization.DataContract(Name=@"ListOfPerson")]
  public partial class ListOfPerson : global::ProtoBuf.IExtensible
  {
    public ListOfPerson() {}
    
    private readonly global::System.Collections.Generic.List<DataTransferObjectLibrary.Person> _PersonList = new global::System.Collections.Generic.List<DataTransferObjectLibrary.Person>();
    [global::ProtoBuf.ProtoMember(1, Name=@"PersonList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"PersonList", Order = 1, IsRequired = false)]
    
    public global::System.Collections.Generic.List<DataTransferObjectLibrary.Person> PersonList
    {
      get { return _PersonList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}